# Generated by Django 4.2.4 on 2024-01-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_date_joined_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
