# Generated by Django 4.2.4 on 2024-01-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_inventory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='Add A Name To Your Inventory', max_length=20),
        ),
    ]
