# Generated by Django 4.2.4 on 2024-01-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_inventory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='pname',
        ),
    ]
